# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='post2',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
