# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170917_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post2',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
