# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment1_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
