# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_shirts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='url_post',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
