# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180430_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='url_post',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
