# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_flags_match_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_results',
            name='country1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country10',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country5',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country6',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country7',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country8',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='country9',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='match1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='match2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='match3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='match4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='match5',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='result_1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='result_2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='result_3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='result_4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='result_5',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
