# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180608_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_1', models.CharField(default=None, max_length=100)),
                ('result', models.CharField(default=None, max_length=100)),
                ('country_2', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='match_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idd', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='all_matches',
            name='match_date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.match_dates'),
        ),
    ]
