# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180613_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=250)),
                ('server_url', models.CharField(max_length=350)),
                ('server_id', models.IntegerField(default=0)),
                ('published', models.BooleanField()),
            ],
        ),
    ]
