# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_servers'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(default=None, max_length=255)),
                ('post_pic', models.CharField(default=None, max_length=255)),
                ('small_caption', models.CharField(default=None, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
