# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_insta_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
