# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190103_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='expiry',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
